# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/learn_nanogpt',
                'doc_host': 'https://pankaj-kvhld.github.io',
                'git_url': 'https://github.com/pankaj-kvhld/learn_nanogpt',
                'lib_path': 'learn_nanogpt'},
  'syms': {'learn_nanogpt.core': {'learn_nanogpt.core.foo': ('core.html#foo', 'learn_nanogpt/core.py')}}}
